### ISSUE TITLE
当日更新した issue, PR の情報が出力されない

### ISSUE THREAD

**Issue by sakamossan** [masutaka/github-nippou#189]
いつも使わせていただいてます。ありがとうございます。
自分の手元で期待通り動作しなくなったのでレポートします。

もし FAQ などありましたら教えてください。

# 症状

コマンドを叩いても、当日に更新した issue や PR が出力されなくなりました。

```console
$ github-nippou | wc -l
       0
```

`--since-date` オプションに昨日を渡すと、昨日に更新した issue や PR は出力されます。
ただし、当日に更新したものは出力されません。

```console
$ github-nippou --since-date "$(gdate --date '1 day ago' +'%Y%m%d')"

### xxxxx/xxx

* ...
* ...

...(中略)
```

OS のアップデート(macOS sonoma)をした直後だったのでタイムゾーンかなと思いましたが、
タイムゾーンは変わっていませんでした。

```console
$ sudo systemsetup -gettimezone
Time Zone: Asia/Tokyo
```

# 動作環境

brew 経由でインストールしています。

```console
$ github-nippou version
4.2.4 (built with go1.21.3)
```

念の為あたらしいものもビルドして試しましたが同様の症状でした。(当日のものは出力されない)

```
$ ~/go/bin/github-nippou version
4.2.28 (built with go1.22.5)
```

`github-nippou init` も済みとのことでした。

```console
$ github-nippou init
** github-nippou Initialization **

== [Step: 1/3] GitHub user ==

Already initialized. You can get it with the following command.

    $ git config --global github-nippou.user


== [Step: 2/3] GitHub personal access token ==

To get new token with `repo` and `gist` scope, visit
https://github.com/settings/tokens/new

Already initialized. You can get it with the following command.

    $ git config --global github-nippou.token


== [Step: 3/3] Gist (optional) ==

Already initialized. You can get it with the following command.

    $ git config --global github-nippou.settings-gist-id

And you can easily open the gist URL with web browser.

    $ github-nippou open-settings

```

apple シリコンの macOS で利用しています。

```console
$ sw_vers
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
$ system_profiler SPHardwareDataType | perl -wnlE '/Hardware Overview/ ... /OS Loader Version/ and say'
    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Mac14,3
      Model Number: Z16L0005HJ/A
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 24 GB
      System Firmware Version: 10151.121.1
      OS Loader Version: 10151.121.1
```

**Comment by masutaka** [comment]
@sakamossan

ご利用ありがとうございます！私も毎日、macOS 14.5 (Sonoma) で、Homebrew でインストールした最新の github-nippou v4.2.28 を使っているので、何か変ですね。

違いはハードウェアだけです。

```console
$ system_profiler SPHardwareDataType | perl -wnlE '/Hardware Overview/ ... /OS Loader Version/ and say'
    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,9
      Model Number: Z17G002KAJ/A
      Chip: Apple M2 Pro
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 32 GB
      System Firmware Version: 10151.121.1
      OS Loader Version: 10151.121.1
```

> コマンドを叩いても、当日に更新した issue や PR が出力されなくなりました。

`--debug` をつけると、GitHub の生に近い API レスポンスが出力されます。github-nippou はこの出力を整形しています。

```
$ github-nippou --debug
```

このレスポンスが出力されれば github-nippou の問題、出力されなければ GitHub の問題に切り分けられます。

いかがでしょうか？

**Comment by sakamossan** [comment]
@masutaka 

`debug` オプションをつけてみましたが、やはり出力はありませんでした。

```console
$ github-nippou --debug
$ github-nippou --debug | wc -c
       0
```

API レスポンス自体が empty ということになると、自分の GitHub アカウントに起因している可能性が高そうです。個人的で広く発生しているものでもないと調査も困難となるかと思うので issue としては close します。

なにかわかりましたらまた追記します。素早くサポートしていただきありがとうございました 😄

**Comment by masutaka** [comment]
@sakamossan
なるほど。ご報告ありがとうございました。

ちなみに使用している API は [List events for the authenticated user](https://docs.github.com/ja/rest/activity/events?apiVersion=2022-11-28#list-events-for-the-authenticated-user) です。時々遅延があり、直近活動した Issue/PR が出てこないことは体験しています。

* https://github.com/masutaka/github-nippou/blob/v4.2.28/lib/events.go#L38
    * https://github.com/google/go-github/blob/v60.0.0/github/activity_events.go#L142-L150
        * https://docs.github.com/ja/rest/activity/events?apiVersion=2022-11-28#list-events-for-the-authenticated-user

🔗 [イベント用 REST API エンドポイント \- GitHub Docs](https://docs.github.com/ja/rest/activity/events?apiVersion=2022-11-28)

> 過去 90 日以内に作成されたイベントのみがタイムラインに含まれます。 90 日以上経過しているイベントは含まれません（タイムラインのイベントの総数が300 未満の場合でも）。

GitHub Event には上記制限はありますが、今日のイベントが出てこないこととは関係ないですね🤔

**Comment by sakamossan** [comment]
先ほど `github-nippou` 動作が復帰しました。

大変うれしいのですが、意図的になにかいじったわけでもなく復帰したもので、なぜ回復したのかわかっていません。
やはりGitHubアカウント起因の問題だったのでしょうか? 情報に乏しくてすいません。

かさねてサポートに感謝します。ありがとうございました。

**Comment by masutaka** [comment]
@sakamossan おお、良かったです！

> やはりGitHubアカウント起因の問題だったのでしょうか? 

`$ github-nippou --debug` でも API レスポンスを確認できるのですよね。
であれば、多分そうですね。PAT (Personal Access Token) の失効ならエラーメッセージが出そうですし...。
私もﾖｸﾜｶﾗﾅｲﾃﾞｽ😅

**Comment by masutaka** [comment]
私も今日から再現しました。日報書くのが面倒です...。😇
社内でも再現している人がイました。

GitHub 側の問題なので、何も出来ることはありませんが、issue（課題）可視化の観点から Reopen しておきます。

**Comment by masutaka** [comment]
8 時間前に活動した PR がようやくひとつ出てきた。今日の私のアカウントは 8 時間程度遅延している様子。

**Comment by masutaka** [comment]
https://support.github.com/ から問い合わせてみた。

```
Title:
Event reflection to REST API "List events for the authenticated user" is delayed

Body:
## Problem

Since the beginning of this month (2024/07), the [List events for the authenticated user](https://docs.github.com/ja/rest/activity/events?apiVersion=2022-11-28#list-events-for-the-authenticated-user) API seems to be delayed.

* I have a feeling that my Events will not be returned as an API response until about 8 hours have passed.
* Depending on the GitHub account you are logged in as, it may or may not be delayed.
* https://www.githubstatus.com/ doesn't seem to be reporting any failures.

## Wanted to know

* Is GitHub aware of this phenomenon?
* I'd like to know if there is a workaround.

## Background

I have created my own tool called github-nippou for writing daily reports and use it daily.

Users have reported this phenomenon and I have been encountering this phenomenon since last week.
https://github.com/masutaka/github-nippou/issues/189 (In Japanese)
```

**Comment by masutaka** [comment]
:link: [REST API endpoints for events \- GitHub Docs](https://docs.github.com/en/rest/activity/events?apiVersion=2022-11-28)

> This API is not built to serve real-time use cases. Depending on the time of day, event latency can be anywhere from 30s to 6h.

上記の通り、[List events for the authenticated user](https://docs.github.com/ja/rest/activity/events?apiVersion=2022-11-28#list-events-for-the-authenticated-user) API には 30 秒から 6 時間の遅延があるそうです。

現時点ではこの文言は [List repository events](https://docs.github.com/en/enterprise-cloud@latest/rest/activity/events?apiVersion=2022-11-28#list-repository-events) API への Note になっていますが、GitHub のサポートに確認したところ全ての Event API に適用されるそうで、ドキュメントの更新に取り組むとのことです。

PR https://github.com/masutaka/github-nippou/pull/194 で本件と、https://github.com/masutaka/github-nippou/issues/189#issuecomment-2210250522 に書いた、90 日以内またはイベント数 300 の制限を README.md に追記しました。

github-nippou 側で出来ることはないのと、README.md に追記したのでクローズします。
